---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sa
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
   name: {{ .Release.Name }}-role
rules:
 - apiGroups: [""]
   resources: ["secrets"]
   verbs:
      - create
      - update
      - get
      - list
      - delete
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
   name: {{ .Release.Name }}-role-binding
subjects:
 - kind: ServiceAccount
   name: {{ .Release.Name }}-sa
   namespace: {{ .Release.Namespace }}
roleRef:
   kind: Role
   name: {{ .Release.Name }}-role
   apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-create-secret
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-create-secret
    spec:
      restartPolicy: Never
      serviceAccountName: {{ .Release.Name }}-sa
      containers:
      - name: create-secret-job
        image: "bitnami/kubectl:latest"
        command:
         - "/bin/sh"
         - "-c"
         - |
             sleep 10;
             kubectl create secret generic sanjay-test-secret --from-literal=username=sanjay;
