---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sa
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
   name: {{ .Release.Name }}-role
rules:
 - apiGroups: [""]
   resources: ["pods"]
   verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
   name: {{ .Release.Name }}-role-binding
subjects:
 - kind: ServiceAccount
   name: {{ .Release.Name }}-sa
   namespace: {{ .Release.Namespace }}
roleRef:
   kind: Role
   name: {{ .Release.Name }}-role
   apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
data:
  name: c2FuamF5
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
