---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-sa-delete-hook
  namespace: {{ .Release.Namespace }}
  annotations:
       "helm.sh/hook": post-delete
       "helm.sh/hook-weight": "3"
       "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Release.Name }}-role-delete-hook
  namespace: {{ .Release.Namespace }}
  annotations:
       "helm.sh/hook": post-delete
       "helm.sh/hook-weight": "4"
       "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
rules:
 - apiGroups: [""]
   resources: ["secrets"]
   verbs: ["get", "list", "watch","delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
   name: {{ .Release.Name }}-rb-delete-hook
   namespace: {{ .Release.Namespace }}
   annotations:
      "helm.sh/hook": post-delete
      "helm.sh/hook-weight": "5"
      "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
subjects:
 - kind: ServiceAccount
   name: {{ .Release.Name }}-sa-delete-hook
   namespace: {{ .Release.Namespace }}
roleRef:
   kind: Role
   name: {{ .Release.Name }}-role-delete-hook
   apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-post-delete
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "6"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-post-delete
    spec:
      restartPolicy: Never
      serviceAccountName: {{ .Release.Name }}-sa-delete-hook
      containers:
      - name: post-delete-job
        image: "bitnami/kubectl:latest"
        command:
         - "/bin/sh"
         - "-c"
         - |
             kubectl delete secret sanjay-test-secret;
             sleep 10;
